name: Build and Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code (needed only for actions context; actual code runs on server)
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up SSH key for deployment
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 145.79.12.143 >> ~/.ssh/known_hosts
      # 3️⃣ Connect to VPS and run pull + docker compose
      - name: Deploy on VPS
        run: |
          ssh root@145.79.12.143 << 'EOF'
            set -e  # exit if any command fails
            cd /var/www/wserver
            echo "Pulling latest code..."
            git pull origin main
            echo "Building Docker images..."
            pm2 stop wserver
            echo "Restarting services..."
            cd dist
            pm2 start index.js --name wserver
            echo "Deployment finished!"
          EOF
